set(VS_PLATFORM_TOOLSET_VERSION "14.29.30133")
set(CMAKE_SYSTEM_PROCESSOR X86)

set(CMAKE_C_COMPILER_FRONTEND_VARIANT MSVC)
set(CMAKE_CXX_COMPILER_FRONTEND_VARIANT MSVC)

include("${CMAKE_CURRENT_LIST_DIR}/WindowsToolchain/Windows.Clang.toolchain.cmake")
